"""Agent context retrieval and run logging."""

import datetime
import json
import struct
from pathlib import Path

from mcp.types import TextContent

from metis_mcp.config import paths
from metis_mcp.db import connect
from metis_mcp.app_instance import app
import logging

log = logging.getLogger("metis.agents")

_AGENT_RUNS_DDL = """
CREATE TABLE IF NOT EXISTS agent_runs (
    run_id INTEGER PRIMARY KEY AUTOINCREMENT,
    agent_slug TEXT NOT NULL,
    task_summary TEXT NOT NULL,
    input_path TEXT DEFAULT '',
    output_path TEXT DEFAULT '',
    status TEXT DEFAULT 'completed',
    created_at TEXT NOT NULL,
    input_tokens INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    model TEXT DEFAULT ''
)
"""

_AGENT_RUNS_MIGRATE = [
    "ALTER TABLE agent_runs ADD COLUMN input_tokens INTEGER DEFAULT 0",
    "ALTER TABLE agent_runs ADD COLUMN output_tokens INTEGER DEFAULT 0",
    "ALTER TABLE agent_runs ADD COLUMN model TEXT DEFAULT ''",
    "ALTER TABLE agent_runs ADD COLUMN session_id TEXT DEFAULT ''",
]


@app.tool()
async def get_agent_context(agent_slug: str) -> list[TextContent]:
    """Load an agent's system prompt, contract, skill and project contexts from the RC.

    Reads system-prompt.md, contract.md, skill.md and every *-context.md from
    agents/{agent_slug}/. The context files carry the project-specific detail —
    methodology parameters, pipeline inventories, past decisions — that turns a
    generic specialist into one that knows this researcher's actual work.
    If the agent is not found, lists all available agents.

    Args:
        agent_slug: Folder name of the agent (e.g. "archivist", "librarian").
    """
    agent_dir = paths.agents / agent_slug

    if not agent_dir.is_dir():
        # List available agents
        try:
            available = sorted(
                d.name for d in paths.agents.iterdir() if d.is_dir() and not d.name.startswith(".")
            )
        except FileNotFoundError:
            return [TextContent(type="text", text=f"Agents directory not found: {paths.agents}")]

        return [
            TextContent(
                type="text",
                text=f"Agent '{agent_slug}' not found.\n\nAvailable agents:\n"
                + "\n".join(f"- {a}" for a in available),
            )
        ]

    parts = []

    # THE HOUSE VOICE COMES FIRST — H4, open from 2026-06-20 to 2026-09-14.
    #
    # `metis-persona.md` is the voice contract: who the researcher is, and how
    # Metis speaks to him (plain English, warm, never condescending). It is
    # documented in CLAUDE.md, published in the README, regenerated by the config
    # wizard — and it was loaded into nothing. Every specialist received its role
    # and its rules and no instruction about how to sound, so the single largest
    # documented-versus-enforced gap in the system was the one governing every
    # sentence the researcher actually reads.
    #
    # FIRST, not last, and that ordering is the point: the agent's own prompt and
    # its project contexts are appended after, so a specialist REFINES the house
    # voice rather than replacing it. Same reasoning as the context files below.
    #
    # Absent or unreadable is not an error. A persona file is per-installation and
    # a fresh clone has none; an agent with no voice contract is how it behaved
    # for the three months before this line existed.
    # BOTH FILES, because the persona alone is half the contract. It is 33 lines
    # describing WHO the researcher is, and its only "how to answer" section is a
    # pointer to the response contract — which is where the voice actually lives.
    # Loading the pointer and not its target is the same shape of gap this fix
    # exists to close, one file further along.
    for _name, _why in (("metis-persona.md", "who this researcher is"),
                        ("metis-response-contract.md", "how to answer him")):
        try:
            fp = paths.root / "system" / "config" / _name
            if fp.exists():
                parts.append(f"# {_name} — {_why}\n\n"
                             + fp.read_text(encoding="utf-8"))
        except Exception as exc:  # noqa: BLE001
            log.warning("agent context: could not read %s (%s)", _name, exc)

    for filename in ("system-prompt.md", "contract.md"):
        fp = agent_dir / filename
        if fp.exists():
            try:
                parts.append(f"# {filename}\n\n{fp.read_text(encoding='utf-8')}")
            except Exception as e:
                parts.append(f"# {filename}\n\nError reading file: {e}")

    # Also include the agent's skill.md (Keystone P3.4). This is where approved
    # self-improvement proposals are written (self_improvement._skill_path resolves
    # .claude/skills/<slug>/skill.md, else agents/<slug>/skill.md). Without reading it
    # here, an "applied" improvement never reached the context the pipeline injects —
    # so "applied" did not mean "in effect". Same precedence as the writer.
    skill_fp = paths.root / ".claude" / "skills" / agent_slug / "skill.md"
    if not skill_fp.exists():
        skill_fp = agent_dir / "skill.md"
    if skill_fp.exists():
        try:
            parts.append(f"# skill.md\n\n{skill_fp.read_text(encoding='utf-8')}")
        except Exception as e:
            parts.append(f"# skill.md\n\nError reading file: {e}")

    # Project context files: agents/<slug>/*-context.md.
    #
    # WHY THIS WAS ADDED (2026-08-17)
    #   Eleven of these files existed — ~44 KB, including the 187-line
    #   hat-metric-context.md that opens "This file is loaded automatically by
    #   Methods Coach at the start of any session involving HAT risk mapping".
    #   Nothing in the codebase referenced any of them. They were written, never
    #   read: the best methodological record in the system was reachable only by
    #   opening the file by hand, and completely invisible from Claude Desktop.
    #
    #   The same write-path-with-no-reader shape as session decisions. A document
    #   that asserts it is loaded automatically is not evidence that it is.
    #
    # Sorted so the injected context is stable between calls; a project-specific
    # file is appended AFTER the generic prompt so it refines rather than
    # competes with it.
    for ctx_fp in sorted(agent_dir.glob("*-context.md")):
        try:
            parts.append(f"# {ctx_fp.name}\n\n{ctx_fp.read_text(encoding='utf-8')}")
        except Exception as e:
            parts.append(f"# {ctx_fp.name}\n\nError reading file: {e}")

    # STANDING DECISIONS — the part that makes invoking a specialist worth doing.
    #
    # Added 2026-08-24, after: "I don't see them mentioned in the outputs, where
    # are my agents? ... if you are not using them they must not be good?"
    #
    # They were not bad; they were empty. `user_decisions` held TWO rows while
    # session summaries held 7,578 decision entries, so this call returned a
    # persona that could be guessed from the agent's name and nothing about how
    # the researcher actually wants things done. Routing therefore cost tokens and
    # added nothing, and anything with judgement stops routing.
    #
    # Injected LAST, after the generic prompt and the project context, because a
    # settled decision should override a general instruction rather than argue
    # with it. Empty string when there is nothing — a heading with nothing under
    # it trains the reader to skip the section.
    try:
        from metis_mcp.tools.agent_memory import render_for_prompt
        decisions = render_for_prompt(agent_slug)
        if decisions:
            parts.append(decisions)
    except Exception as exc:  # noqa: BLE001 — never let memory break the context
        parts.append(f"# standing decisions\n\nunavailable: {exc}")

    # The model this agent DECLARES it wants. Reported, never enforced:
    # `user_decisions` #2, 2026-08-12 — "Model tiering stays ADVISORY, not
    # binding — Metis does not make the answer's model call, the Claude client
    # does. Do not re-litigate without new reasons." Surfacing it means a stale
    # declaration is visible instead of silently wrong, which is what it was:
    # 16 agents declared a model a generation behind, and nothing read the field.
    try:
        import re as _re
        for _f in ("skill.md", "system-prompt.md"):
            _fp = agent_dir / _f
            if not _fp.exists():
                continue
            _m = _re.search(r"^model:\s*(\S+)", _fp.read_text(encoding="utf-8"),
                            _re.MULTILINE)
            if _m:
                parts.append(
                    f"# declared model\n\n`{_m.group(1)}` (advisory — the client "
                    "chooses the model; this is what the agent was written for)")
                break
    except Exception:
        pass

    if not parts:
        return [
            TextContent(
                type="text",
                text=f"No system-prompt.md or contract.md found in {agent_dir}",
            )
        ]

    return [TextContent(type="text", text="\n\n---\n\n".join(parts))]


@app.tool()
async def log_agent_run(
    agent_slug: str,
    task_summary: str,
    input_path: str = "",
    output_path: str = "",
    complexity: str = "standard",
    input_tokens: int = 0,
    output_tokens: int = 0,
    model: str = "",
    session_id: str = "",
) -> list[TextContent]:
    """Log a completed agent run to the database for audit and dashboard tracking.

    Records that an agent did a piece of work so it appears in the dashboard's
    Agents view and in get_agent_runs. Call it after writing an output file, per
    the output contract. When a session_id is supplied it also writes a "result"
    event to session_events, closing the loop for /metis pipeline calls.

    Args:
        agent_slug: Slug of the agent that performed the work (e.g. "librarian").
        task_summary: Brief description of what the agent did.
        input_path: Path to the input file(s), if any (default empty string).
        output_path: Path to the output file(s) produced, if any (default empty).
        complexity: The run status stored in the `status` column — typically
            "completed", "partial", or "failed" (default "standard").
        input_tokens: Input tokens consumed, for cost tracking (default 0).
        output_tokens: Output tokens produced, for cost tracking (default 0).
        model: Model identifier used, e.g. "claude-sonnet-4-6" (default empty).
        session_id: Pipeline session ID from session_bootstrap(); when set, also
            records a result event in session_events (default empty string).

    Returns:
        A confirmation message naming the agent and task that were logged.
    """
    if not paths.db.exists():
        return [TextContent(type="text", text=f"Database not found: {paths.db}")]

    try:
        with connect(paths.db) as conn:
            conn.execute(_AGENT_RUNS_DDL)
            # Migrate existing tables that predate token tracking columns
            for stmt in _AGENT_RUNS_MIGRATE:
                try:
                    conn.execute(stmt)
                except Exception:
                    pass  # Column already exists
            _now = datetime.datetime.now(datetime.timezone.utc).isoformat()
            # S.2: if run_metis dispatch-wrote a 'running' row for this session,
            # complete THAT row instead of inserting a duplicate — so the live
            # "who's working now" resolves to a single finished run. Preserve the
            # dispatch-written model when the completion call doesn't supply one.
            #
            # Matching includes agent_slug. Routing may put several specialists on
            # one request, so a session can hold several open 'running' rows; a
            # session-only match would close whichever was newest and relabel it
            # with THIS agent's name, silently losing one agent and duplicating
            # another. Fall back to a session-only match so a run dispatched under
            # a different slug still completes rather than orphaning.
            _updated = False
            if session_id:
                for _where, _args in (
                    ("session_id=? AND agent_slug=? AND status='running'", (session_id, agent_slug)),
                    ("session_id=? AND status='running'", (session_id,)),
                ):
                    cur = conn.execute(
                        f"""UPDATE agent_runs
                              SET agent_slug=?, task_summary=?, input_path=?, output_path=?,
                                  status=?, created_at=?, input_tokens=?, output_tokens=?,
                                  model=CASE WHEN ?='' THEN model ELSE ? END
                            WHERE rowid = (
                                  SELECT rowid FROM agent_runs
                                   WHERE {_where}
                                   ORDER BY created_at DESC, rowid DESC LIMIT 1)""",
                        (
                            agent_slug, task_summary, input_path, output_path,
                            complexity, _now, input_tokens, output_tokens,
                            model, model, *_args,
                        ),
                    )
                    _updated = (cur.rowcount or 0) > 0
                    if _updated:
                        break
            if not _updated:
                conn.execute(
                    """INSERT INTO agent_runs
                       (agent_slug, task_summary, input_path, output_path, status, created_at,
                        input_tokens, output_tokens, model, session_id)
                       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                    (
                        agent_slug,
                        task_summary,
                        input_path,
                        output_path,
                        complexity,
                        _now,
                        input_tokens,
                        output_tokens,
                        model,
                        session_id,
                    ),
                )
            conn.commit()

            # Also write to session_events when this run is part of a pipeline session.
            # This closes the loop for /metis calls: run_metis writes turn + routing events,
            # the executing agent then calls log_agent_run which writes the result event.
            if session_id:
                try:
                    conn.execute(
                        """INSERT INTO session_events (session_id, event_type, content, created_at)
                           VALUES (?, 'result', ?, ?)""",
                        (
                            session_id,
                            f"[{agent_slug}] {task_summary[:500]}",
                            datetime.datetime.now(datetime.timezone.utc).isoformat(),
                        ),
                    )
                    conn.commit()
                except Exception:
                    pass  # session_events write is best-effort — don't fail the log

        # ── Phase B: Automatic memory extraction ──────────────────────────
        # Write an episodic memory entry immediately so findings are
        # searchable right away — don't wait for nightly consolidation.
        try:
            _auto_extract_memory(
                conn, agent_slug, task_summary, output_path, session_id
            )
        except Exception:
            pass  # Memory extraction is best-effort — never fail the log

        return [
            TextContent(
                type="text",
                text=f"Logged run for agent '{agent_slug}': {task_summary}",
            )
        ]
    except Exception as e:
        return [TextContent(type="text", text=f"Error logging agent run: {e}")]


def _auto_extract_memory(
    conn, agent_slug: str, task_summary: str,
    output_path: str, session_id: str,
) -> None:
    """Extract and store an episodic memory entry from an agent run.

    Writes to episodic_memory with agent_id scope so the agent accumulates
    its own searchable history. If the run produced an output file, reads
    its first 1500 chars and indexes those too.
    """
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()

    # Build the content to remember
    content_parts = [f"Agent run: {agent_slug}"]
    content_parts.append(f"Task: {task_summary}")

    # Read output file excerpt if it exists
    output_excerpt = ""
    if output_path:
        try:
            fp = paths.root / output_path
            if fp.exists() and fp.suffix in (".md", ".txt", ".json", ".yaml", ".yml"):
                raw = fp.read_text(encoding="utf-8", errors="ignore")[:1500]
                output_excerpt = raw
                content_parts.append(f"Output excerpt: {raw[:500]}")
        except Exception:
            pass

    content = "\n".join(content_parts)
    metadata = json.dumps({
        "agent_slug": agent_slug,
        "output_path": output_path,
        "auto_extracted": True,
    })

    # Ensure vector memory tables exist
    try:
        from metis_mcp.tools.vector_memory import _setup_tables
        _setup_tables(conn)
    except Exception:
        return

    # Insert episodic memory with agent scope
    cur = conn.execute(
        """INSERT INTO episodic_memory
           (session_id, event_type, content, metadata, created_at,
            agent_id, project_id, scope)
           VALUES (?, 'agent_run', ?, ?, ?, ?, '', 'agent')""",
        (session_id, content, metadata, now, agent_slug),
    )
    row_id = cur.lastrowid

    # Embed and index for vector search
    try:
        from metis_mcp.embeddings import embed_document
        vector = embed_document(content[:2000])
        conn.execute(
            "INSERT INTO vec_episodic (rowid, embedding) VALUES (?, ?)",
            (row_id, struct.pack(f"{len(vector)}f", *vector)),
        )
    except (ImportError, Exception):
        pass  # Store without embedding — still keyword-searchable

    conn.commit()


@app.tool()
async def get_agent_runs(
    limit: int = 10,
    since: str = "",
    agent_slug: str = "",
) -> list[TextContent]:
    """Retrieve recent agent run history from the database.

    Returns the log of past agent work — what ran, when, its status, and token
    usage — for the dashboard or for reviewing recent activity. These rows are
    written by log_agent_run. Results come back newest first.

    Args:
        limit: Maximum number of runs to return, newest first (default 10).
        since: ISO date or datetime string; only runs at or after this time are
            returned. Empty string (default) returns runs from all dates.
        agent_slug: Filter to a single agent by slug, e.g. "librarian" or
            "metis". Empty string (default) returns all agents.

    Returns:
        A text block listing the matching runs (run_id, agent, task summary,
        status, timestamp, token counts, model).
    """
    if not paths.db.exists():
        return [TextContent(type="text", text="Database not found.")]

    conditions: list[str] = []
    params: list = []
    if since:
        conditions.append("created_at >= ?")
        params.append(since)
    if agent_slug:
        conditions.append("agent_slug = ?")
        params.append(agent_slug)

    where = f"WHERE {' AND '.join(conditions)}" if conditions else ""
    params.append(limit)

    try:
        with connect(paths.db) as conn:
            conn.execute(_AGENT_RUNS_DDL)
            rows = conn.execute(
                f"SELECT run_id, agent_slug, task_summary, status, created_at, "
                f"input_tokens, output_tokens, model "
                f"FROM agent_runs {where} ORDER BY created_at DESC LIMIT ?",
                params,
            ).fetchall()
    except Exception as e:
        return [TextContent(type="text", text=f"Error reading agent runs: {e}")]

    if not rows:
        return [TextContent(type="text", text="No agent runs found.")]

    lines = [f"{len(rows)} run(s):\n"]
    for r in rows:
        tokens = (r["input_tokens"] or 0) + (r["output_tokens"] or 0)
        tok_str = f" · {tokens:,} tok" if tokens else ""
        model_str = f" · {r['model']}" if r["model"] else ""
        lines.append(
            f"[{r['agent_slug']}] {(r['task_summary'] or '')[:80]}\n"
            f"  {(r['created_at'] or '')[:16]} · {r['status']}{tok_str}{model_str}"
        )
    return [TextContent(type="text", text="\n\n".join(lines))]
